-- Phase 1b: seed all Telangana urban local bodies (135 = 12 municipal corporations + 123 municipalities).
-- Requires phase 1 districts. Idempotent on (district_id, slug).
-- Source: Wikipedia "List of urban local bodies in Telangana" (CDMA-aligned corps + municipalities).
-- Keep in sync with src/lib/data/urban-directory.json
-- Note: Secunderabad Cantonment Board omitted (not a CDMA ULB).
-- Multi-district corps are anchored to a primary district_slug for routing.

WITH d AS (SELECT id, slug FROM districts),
v(district_slug, slug, name_en, name_te, ulb_type, town_coordinators_count, registered_establishments_count, welfare_support_active) AS (
  VALUES
    ('adilabad', 'adilabad-municipality', 'Adilabad Municipality', 'ఆదిలాబాద్ మున్సిపాలిటీ', 'municipality', 2, 36, true),
    ('bhadradri-kothagudem', 'aswaraopeta-municipality', 'Aswaraopeta Municipality', 'అశ్వారావుపేట మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('bhadradri-kothagudem', 'kothagudem-municipal-corporation', 'Kothagudem Municipal Corporation', 'కొత్తగూడెం మున్సిపల్ కార్పొరేషన్', 'municipal_corporation', 0, 0, true),
    ('bhadradri-kothagudem', 'manuguru-municipality', 'Manuguru Municipality', 'మణుగూరు మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('bhadradri-kothagudem', 'yellandu-municipality', 'Yellandu Municipality', 'ఎల్లందు మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('hanumakonda', 'warangal-municipal-corporation', 'Greater Warangal Municipal Corporation', 'గ్రేటర్ వరంగల్ మున్సిపల్ కార్పొరేషన్', 'municipal_corporation', 0, 0, true),
    ('hanumakonda', 'parkal-municipality', 'Parkal Municipality', 'పర్కాల మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('hyderabad', 'hyderabad-municipal-corporation', 'Greater Hyderabad Municipal Corporation', 'గ్రేటర్ హైదరాబాద్ మున్సిపల్ కార్పొరేషన్', 'municipal_corporation', 4, 128, true),
    ('jagtial', 'dharmapuri-municipality', 'Dharmapuri Municipality', 'ధర్మపురి మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('jagtial', 'jagtial-municipality', 'Jagtial Municipality', 'జగిత్యాల మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('jagtial', 'korutla-municipality', 'Korutla Municipality', 'కోరుట్ల మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('jagtial', 'metpally-municipality', 'Metpally Municipality', 'మెట్ పల్లి మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('jagtial', 'raikal-municipality', 'Raikal Municipality', 'రాయికల్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('jangaon', 'jangaon-municipality', 'Jangaon Municipality', 'జనగాం మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('jangaon', 'station-ghanpur-municipality', 'Station Ghanpur Municipality', 'స్టేషన్ ఘన్‌పూర్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('jayashankar-bhupalpally', 'bhupalpally-municipality', 'Bhupalpally Municipality', 'భూపాల్ పల్లి మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('jogulamba-gadwal', 'alampuram-municipality', 'Alampuram Municipality', 'ఆలంపూర్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('jogulamba-gadwal', 'gadwal-municipality', 'Gadwal Municipality', 'గద్వాల్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('jogulamba-gadwal', 'ieeja-municipality', 'Ieeja Municipality', 'అయిజ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('jogulamba-gadwal', 'waddepalle-municipality', 'Waddepalle Municipality', 'వడ్డెపల్లి మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('kamareddy', 'banswada-municipality', 'Banswada Municipality', 'బాన్స్ వాడ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('kamareddy', 'bichkunda-municipality', 'Bichkunda Municipality', 'బిచ్కుంద మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('kamareddy', 'kamareddy-municipality', 'Kamareddy Municipality', 'కామారెడ్డి మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('kamareddy', 'yellareddy-municipality', 'Yellareddy Municipality', 'ఎల్లారెడ్డి మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('karimnagar', 'choppadandi-municipality', 'Choppadandi Municipality', 'చొప్పదండి మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('karimnagar', 'huzurabad-municipality', 'Huzurabad Municipality', 'హుజురాబాద్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('karimnagar', 'jammikunta-municipality', 'Jammikunta Municipality', 'జమ్మికుంట మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('karimnagar', 'karimnagar-municipal-corporation', 'Karimnagar Municipal Corporation', 'కరీంనగర్ మున్సిపల్ కార్పొరేషన్', 'municipal_corporation', 0, 0, true),
    ('khammam', 'kallur-municipality', 'Kallur Municipality', 'కల్లూరు మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('khammam', 'khammam-municipal-corporation', 'Khammam Municipal Corporation', 'ఖమ్మం మున్సిపల్ కార్పొరేషన్', 'municipal_corporation', 3, 58, true),
    ('khammam', 'madhira-municipality', 'Madhira Municipality', 'మధిర మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('khammam', 'sathupalli-municipality', 'Sathupalli Municipality', 'సత్తుపల్లి మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('khammam', 'wyra-municipality', 'Wyra Municipality', 'వైరా మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('khammam', 'yedulapuram-municipality', 'Yedulapuram Municipality', 'ఏదులాపురం మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('kumuram-bheem-asifabad', 'asifabad-municipality', 'Asifabad Municipality', 'ఆసిఫాబాద్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('kumuram-bheem-asifabad', 'kagaznagar-municipality', 'Kagaznagar Municipality', 'కాగజ్ నగర్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('mahabubabad', 'dornakal-municipality', 'Dornakal Municipality', 'డోర్నకల్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('mahabubabad', 'kesamudram-municipality', 'Kesamudram Municipality', 'కేసముద్రం మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('mahabubabad', 'mahabubabad-municipality', 'Mahabubabad Municipality', 'మహబూబాబాద్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('mahabubabad', 'maripeda-municipality', 'Maripeda Municipality', 'మరిపెడ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('mahabubabad', 'thorrur-municipality', 'Thorrur Municipality', 'తొర్రూర్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('mahabubnagar', 'bhoothpur-municipality', 'Bhoothpur Municipality', 'బూత్పూర్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('mahabubnagar', 'devarakadra-municipality', 'Devarakadra Municipality', 'దేవర కద్ర మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('mahabubnagar', 'jadcherla-municipality', 'Jadcherla Municipality', 'జడ్చర్ల మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('mahabubnagar', 'mahabubnagar-municipal-corporation', 'Mahabubnagar Municipal Corporation', 'మహబూబ్‌నగర్ మున్సిపల్ కార్పొరేషన్', 'municipal_corporation', 0, 0, true),
    ('mancherial', 'bellampalle-municipality', 'Bellampalle Municipality', 'బెల్లంపల్లి మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('mancherial', 'chennur-municipality', 'Chennur Municipality', 'చెన్నూర్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('mancherial', 'kyathanpally-municipality', 'Kyathanpally Municipality', 'క్యాతంపల్లి మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('mancherial', 'luxettipet-municipality', 'Luxettipet Municipality', 'లక్సెట్టిపేట్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('mancherial', 'mancherial-municipal-corporation', 'Mancherial Municipal Corporation', 'మంచిర్యాల మున్సిపల్ కార్పొరేషన్', 'municipal_corporation', 0, 0, true),
    ('mancherial', 'mandamarri-municipality', 'Mandamarri Municipality', 'మందమర్రి మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('medak', 'medak-municipality', 'Medak Municipality', 'మెదక్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('medak', 'narsapur-municipality', 'Narsapur Municipality', 'నర్సాపూర్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('medak', 'ramayampet-municipality', 'Ramayampet Municipality', 'రామాయంపేట మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('medak', 'toopran-municipality', 'Toopran Municipality', 'తూప్రాన్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('medchal-malkajgiri', 'aliabad-municipality', 'Aliabad Municipality', 'అలియాబాద్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('medchal-malkajgiri', 'malkajgiri-municipal-corporation', 'Malkajgiri Municipal Corporation', 'మల్కాజిగిరి మున్సిపల్ కార్పొరేషన్', 'municipal_corporation', 0, 0, true),
    ('medchal-malkajgiri', 'mudichintalapalle-municipality', 'Mudichintalapalle Municipality', 'ముడిచింతలపల్లె మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('medchal-malkajgiri', 'yellampet-municipality', 'Yellampet Municipality', 'ఎల్లంపేట్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('mulugu', 'mulugu-municipality', 'Mulugu Municipality', 'ములుగు మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('nagarkurnool', 'achampet-municipality', 'Achampet Municipality', 'అచ్చం పేట మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('nagarkurnool', 'kalwakurthy-municipality', 'Kalwakurthy Municipality', 'కల్వకుర్తి మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('nagarkurnool', 'kollapur-municipality', 'Kollapur Municipality', 'కొల్లాపూర్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('nagarkurnool', 'nagarkurnool-municipality', 'Nagarkurnool Municipality', 'నాగర్‌కర్నూల్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('nalgonda', 'chandur-municipality', 'Chandur Municipality', 'Chandur మండలం మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('nalgonda', 'chityal-municipality', 'Chityal Municipality', 'చిట్యాల మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('nalgonda', 'devarakonda-municipality', 'Devarakonda Municipality', 'దేవరకొండ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('nalgonda', 'haliya-municipality', 'Haliya Municipality', 'హాలియా మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('nalgonda', 'miryalaguda-municipality', 'Miryalaguda Municipality', 'మిర్యాలగూడ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('nalgonda', 'nakrekal-municipality', 'Nakrekal Municipality', 'నకిరేకల్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('nalgonda', 'nalgonda-municipal-corporation', 'Nalgonda Municipal Corporation', 'నల్గొండ మున్సిపల్ కార్పొరేషన్', 'municipal_corporation', 0, 0, true),
    ('nalgonda', 'nandikonda-municipality', 'Nandikonda Municipality', 'నందికొండ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('narayanpet', 'kosgi-municipality', 'Kosgi Municipality', 'కోస్గి మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('narayanpet', 'maddur-municipality', 'Maddur Municipality', 'మద్దూరు మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('narayanpet', 'makhtal-municipality', 'Makhtal Municipality', 'మఖ్తల్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('narayanpet', 'narayanpet-municipality', 'Narayanpet Municipality', 'నారాయణపేట మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('nirmal', 'bhainsa-municipality', 'Bhainsa Municipality', 'భైంసా మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('nirmal', 'khanapur-municipality', 'Khanapur Municipality', 'ఖానాపూర్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('nirmal', 'nirmal-municipality', 'Nirmal Municipality', 'నిర్మల్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('nizamabad', 'armoor-municipality', 'Armoor Municipality', 'ఆర్మూర్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('nizamabad', 'bheemgal-municipality', 'Bheemgal Municipality', 'భీంగల్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('nizamabad', 'bodhan-municipality', 'Bodhan Municipality', 'బోధన్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('nizamabad', 'nizamabad-municipal-corporation', 'Nizamabad Municipal Corporation', 'నిజామాబాద్ మున్సిపల్ కార్పొరేషన్', 'municipal_corporation', 0, 0, true),
    ('peddapalli', 'manthani-municipality', 'Manthani Municipality', 'మంథని మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('peddapalli', 'peddapalli-municipality', 'Peddapalli Municipality', 'పెద్దపల్లి మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('peddapalli', 'ramagundam-municipal-corporation', 'Ramagundam Municipal Corporation', 'రామగుండం మున్సిపల్ కార్పొరేషన్', 'municipal_corporation', 0, 0, true),
    ('peddapalli', 'sultanabad-municipality', 'Sultanabad Municipality', 'సుల్తానాబాద్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('rajanna-sircilla', 'sircilla-municipality', 'Sircilla Municipality', 'సిరిసిల్ల మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('rajanna-sircilla', 'vemulawada-municipality', 'Vemulawada Municipality', 'వేములవాడ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('rangareddy', 'amangal-municipality', 'Amangal Municipality', 'అమంగల్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('rangareddy', 'chevella-municipality', 'Chevella Municipality', 'చేవెళ్ళ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('rangareddy', 'cyberabad-municipal-corporation', 'Cyberabad Municipal Corporation', 'సైబరాబాద్ మున్సిపల్ కార్పొరేషన్', 'municipal_corporation', 0, 0, true),
    ('rangareddy', 'ibrahimpatnam-municipality', 'Ibrahimpatnam Municipality', 'ఇబ్రహీంపట్నం మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('rangareddy', 'kothur-municipality', 'Kothur Municipality', 'కోత్తూర్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('rangareddy', 'moinabad-municipality', 'Moinabad Municipality', 'మోయినా బాద్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('rangareddy', 'shadnagar-municipality', 'Shadnagar Municipality', 'షాద్నగర్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('rangareddy', 'shankarpalli-municipality', 'Shankarpalli Municipality', 'శంకరపల్లి మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('sangareddy', 'andole-jogipet-municipality', 'Andole–Jogipet Municipality', 'ఆందోల్-జోగిపేట మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('sangareddy', 'gaddapotharam-municipality', 'Gaddapotharam Municipality', 'గడ్డపోతారం మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('sangareddy', 'gummadidala-municipality', 'Gummadidala Municipality', 'గుమ్మడిదల మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('sangareddy', 'indresham-municipality', 'Indresham Municipality', 'ఇంద్రేశం మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('sangareddy', 'isnapur-municipality', 'Isnapur Municipality', 'ఇస్నాపూర్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('sangareddy', 'jinnaram-municipality', 'Jinnaram Municipality', 'జిన్నారం మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('sangareddy', 'kohir-municipality', 'Kohir Municipality', 'కోహిర్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('sangareddy', 'narayankhed-municipality', 'Narayankhed Municipality', 'నారాయణఖేడ్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('sangareddy', 'sadasivpet-municipality', 'Sadasivpet Municipality', 'సదాశివపేట్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('sangareddy', 'sangareddy-municipality', 'Sangareddy Municipality', 'సంగారెడ్డి మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('sangareddy', 'zaheerabad-municipality', 'Zaheerabad Municipality', 'జహీరాబాద్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('siddipet', 'cheriyal-municipality', 'Cheriyal Municipality', 'చేర్యాల మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('siddipet', 'dubbaka-municipality', 'Dubbaka Municipality', 'దుబ్బాక మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('siddipet', 'gajwel-municipality', 'Gajwel Municipality', 'గజ్వెల్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('siddipet', 'husnabad-municipality', 'Husnabad Municipality', 'హుస్నాబాద్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('siddipet', 'siddipet-municipality', 'Siddipet Municipality', 'సిద్దిపేట మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('suryapet', 'huzurnagar-municipality', 'Huzurnagar Municipality', 'హుజుర్ నగర్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('suryapet', 'kodad-municipality', 'Kodad Municipality', 'కోదాడ్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('suryapet', 'neredcherla-municipality', 'Neredcherla Municipality', 'నేరేడ్ చర్ల మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('suryapet', 'suryapet-municipality', 'Suryapet Municipality', 'సూర్యాపేట మున్సిపాలిటీ', 'municipality', 2, 42, true),
    ('suryapet', 'thirumalagiri-municipality', 'Thirumalagiri Municipality', 'తిర్మలగిరి మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('vikarabad', 'kodangal-municipality', 'Kodangal Municipality', 'కోడంగల్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('vikarabad', 'parigi-municipality', 'Parigi Municipality', 'పరిగి మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('vikarabad', 'tandur-municipality', 'Tandur Municipality', 'తాండూర్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('vikarabad', 'vikarabad-municipality', 'Vikarabad Municipality', 'వికారాబాద్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('wanaparthy', 'amarchinta-municipality', 'Amarchinta Municipality', 'అమరచింత మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('wanaparthy', 'atmakur-municipality', 'Atmakur Municipality', 'ఆత్మకూర్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('wanaparthy', 'kothakota-municipality', 'Kothakota Municipality', 'కోత్తకోట మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('wanaparthy', 'pebbair-municipality', 'Pebbair Municipality', 'పెబ్బెర్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('wanaparthy', 'wanaparthy-municipality', 'Wanaparthy Municipality', 'వనపర్తి మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('warangal', 'narsampet-municipality', 'Narsampet Municipality', 'నర్సంపేట మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('warangal', 'wardhannapet-municipality', 'Wardhannapet Municipality', 'వర్దన్నపేట మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('yadadri-bhuvanagiri', 'alair-municipality', 'Alair Municipality', 'ఆలేరు మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('yadadri-bhuvanagiri', 'bhongir-municipality', 'Bhongir Municipality', 'భూవనగిరి మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('yadadri-bhuvanagiri', 'bhoodan-pochampally-municipality', 'Bhoodan Pochampally Municipality', 'భూదాన్ పోచంపల్లి మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('yadadri-bhuvanagiri', 'choutuppal-municipality', 'Choutuppal Municipality', 'చౌట్టుప్పల్ మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('yadadri-bhuvanagiri', 'mothkur-municipality', 'Mothkur Municipality', 'మోతుకూరు మున్సిపాలిటీ', 'municipality', 0, 0, true),
    ('yadadri-bhuvanagiri', 'yadagirigutta-municipality', 'Yadagirigutta Municipality', 'యాదగిరి గుట్ట మున్సిపాలిటీ', 'municipality', 0, 0, true)
)
INSERT INTO urban_local_bodies (
  district_id, slug, name_en, name_te, ulb_type,
  town_coordinators_count, registered_establishments_count, welfare_support_active
)
SELECT
  d.id,
  v.slug,
  v.name_en,
  v.name_te,
  v.ulb_type,
  v.town_coordinators_count,
  v.registered_establishments_count,
  v.welfare_support_active
FROM v
JOIN d ON d.slug = v.district_slug
ON CONFLICT (district_id, slug) DO UPDATE SET
  name_en = EXCLUDED.name_en,
  name_te = EXCLUDED.name_te,
  ulb_type = EXCLUDED.ulb_type,
  town_coordinators_count = EXCLUDED.town_coordinators_count,
  registered_establishments_count = EXCLUDED.registered_establishments_count,
  welfare_support_active = EXCLUDED.welfare_support_active;
