#!/usr/bin/env python3
"""Validate representationCivicTemplates.json (checksum helper).

NOTE: The live petition UI lives in src/components/RepresentationLetterPage.tsx
and is NOT fully regenerated by this script. Do not overwrite that file with a
naive dump — it includes TWA/mobile PDF download (html2canvas + jspdf), the
External Browser floating button, translate=\"no\" / lang=\"te\" on the printable
card, and A4 single-page print containment. Keep those behaviors when regenerating.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "src/lib/data/representationCivicTemplates.json"
OUT = ROOT / "src/components/RepresentationLetterPage.tsx"
PRINT_HELPER = ROOT / "src/lib/twa/printPetitionPdf.ts"


def main() -> None:
    payload = json.loads(DATA.read_text(encoding="utf-8"))
    templates = payload["templates"]
    ui = payload["ui"]
    assert templates and ui["heading"]
    assert OUT.exists(), f"missing live page {OUT}"
    assert PRINT_HELPER.exists(), f"missing TWA print helper {PRINT_HELPER}"
    live = OUT.read_text(encoding="utf-8")
    for needle in (
        "downloadPetitionPdf",
        'translate="no"',
        'lang="te"',
        "print-signature-block",
        "PDF_LOADING_TE",
        "OPEN_EXTERNAL_BROWSER_LABEL",
    ):
        assert needle in live, f"{OUT.name} missing required TWA/print marker: {needle}"
    print(f"OK {len(templates)} templates; heading={ui['heading']!r}")
    print(f"Live page {OUT.name} retains TWA PDF + A4 print containment markers.")
    print(f"Edit {DATA} then patch {OUT.name} carefully — do not wipe print/TWA helpers.")


if __name__ == "__main__":
    main()
